services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      KAFKA_URL: ${KAFKA_URL}
      KAFKA_CLIENT_CERT: ${KAFKA_CLIENT_CERT}
      KAFKA_CLIENT_CERT_KEY: ${KAFKA_CLIENT_CERT_KEY}
      KAFKA_TRUSTED_CERT: ${KAFKA_TRUSTED_CERT}
